name: Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: gihub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: commits
        env:
          COMMITS: ${{ toJson(github.event.commits) }}
        run: echo "$COMMITS"
        
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"

      # - name: Bamp version and add tag
      #   uses: anothrNick/github-tag-action@1.34.0
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'

      # - name: npm install
      #   run: npm install

      # - name: Lint
      #   run: npm run eslint

      # - name: Build
      #   run: npm run build

      # - name: Test
      #   run: npm run test

      # - name: E2E tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     command: npm run test:e2e
      #     start: npm run start-prod
      #     wait-on: 'http://localhost:5000'

      # - name: Name of event
      #   run: echo "Event name is ${{ github.event_name }}"

      # - name: Deploy to Heroku
      #   if: github.event_name == 'push'
      #   uses: akhileshns/heroku-deploy@v3.8.9
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: 'fso2020-poket'
      #     heroku_email: 'kolya.ya@gmail.com'
      #     healthcheck: "https://fso2020-poket.herokuapp.com/version"
      #     checkstring: "5"
      #     delay: 5
      #     rollbackonhealthcheckfailed: true