name: Test_&_Deployment pipeline

on:
  push:
    branches:
      - master
  pull_request:
    branches: [master]
    types: [opened, synchronize]

jobs:
  lint_test_deployment_pipeline:
    name: Lint, test and deployment pipeline
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2          

      # - uses: actions/setup-node@v2
      #   with:
      #     node-version: '12'

      # - name: npm install
      #   run: npm install

      # - name: Lint
      #   run: npm run eslint

      # - name: Build
      #   run: npm run build

      # - name: Test
      #   run: npm run test

      # - name: E2E tests
      #   uses: cypress-io/github-action@v2
      #   with:
      #     command: npm run test:e2e
      #     start: npm run start-prod
      #     wait-on: 'http://localhost:5000'

      # - name: Bamp version and add tag
      #   if: github.event_name == 'push' && env.SKIP_VER
      #   uses: anothrNick/github-tag-action@1.34.0
      #   env:
      #     SKIP_VER: ${{ !contains(join(github.event.commits.*.message, ', '), '#skip_ver') }}
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      #     WITH_V: true

      # - name: Deploy to Heroku
      #   if: github.event_name == 'push' && env.SKIP_VER
      #   uses: akhileshns/heroku-deploy@v3.8.9
      #   with:
      #     heroku_api_key: ${{secrets.HEROKU_API_KEY}}
      #     heroku_app_name: 'fso2020-poket'
      #     heroku_email: 'kolya.ya@gmail.com'
      #     healthcheck: "https://fso2020-poket.herokuapp.com/version"
      #     checkstring: "5"
      #     delay: 5
      #     rollbackonhealthcheckfailed: true
      #   env:
      #     SKIP_VER: ${{ !contains(join(github.event.commits.*.message, ', '), '#skip_ver') }}

      # - name: Slack failure notifications
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: ${{ job.status }}
      #     fields: repo,message,commit,author,took
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   if: failure()

      # - name: Slack success notifications
      #   uses: 8398a7/action-slack@v3
      #   with:
      #     status: custom
      #     fields: commit,author,took
      #     custom_payload: |
      #       {
      #         username: 'FSO 2020 Github actions',
      #         icon_emoji: ':hurtrealbad:',
      #         attachments: [{
      #           color: 'good',
      #           text: `A new version deployed to https://fso2020-poket.herokuapp.com.\nCommit: ${process.env.AS_COMMIT} by ${process.env.AS_AUTHOR}.\nBuild took ${process.env.AS_TOOK}.`
      #         }]
      #       }

      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #     SKIP_VER: ${{ !contains(join(github.event.commits.*.message, ', '), '#skip_ver') }}
      #   if: success() && github.event_name == 'push' && env.SKIP_VER